variable "oci_region_abbr_map" {
  type        = map(string)
  description = "Map of Oracle Cloud Infrastructure region identifiers to short abbreviations for naming resources"
  default = {
    "af-casablanca-1" = "lej"
    "af-johannesburg-1" = "jnb"
    "ap-batam-1" = "hsg"
    "ap-chiyoda-1" = "nja"
    "ap-chuncheon-1" = "yny"
    "ap-chuncheon-2" = "bno"
    "ap-dcc-canberra-1" = "wga"
    "ap-dcc-gazipur-1" = "dac"
    "ap-delhi-1" = "onm"
    "ap-hyderabad-1" = "hyd"
    "ap-ibaraki-1" = "ukb"
    "ap-kulai-2" = "jbp"
    "ap-melbourne-1" = "mel"
    "ap-mumbai-1" = "bom"
    "ap-osaka-1" = "kix"
    "ap-seoul-1" = "icn"
    "ap-seoul-2" = "dtz"
    "ap-singapore-1" = "sin"
    "ap-singapore-2" = "xsp"
    "ap-suwon-1" = "dln"
    "ap-sydney-1" = "syd"
    "ap-tokyo-1" = "nrt"
    "ca-montreal-1" = "yul"
    "ca-toronto-1" = "yyz"
    "eu-amsterdam-1" = "ams"
    "eu-budapest-1" = "jsk"
    "eu-crissier-1" = "avf"
    "eu-dcc-dublin-1" = "ork"
    "eu-dcc-dublin-2" = "snn"
    "eu-dcc-milan-1" = "bgy"
    "eu-dcc-milan-2" = "mxp"
    "eu-dcc-rating-1" = "dus"
    "eu-dcc-rating-2" = "dtm"
    "eu-dcc-zurich-1" = "avz"
    "eu-frankfurt-1" = "fra"
    "eu-frankfurt-2" = "str"
    "eu-jovanovac-1" = "beg"
    "eu-madrid-1" = "mad"
    "eu-madrid-2" = "vll"
    "eu-madrid-3" = "orf"
    "eu-marseille-1" = "mrs"
    "eu-milan-1" = "lin"
    "eu-paris-1" = "cdg"
    "eu-stockholm-1" = "arn"
    "eu-turin-1" = "nrq"
    "eu-zurich-1" = "zrh"
    "il-jerusalem-1" = "mtz"
    "me-abudhabi-1" = "auh"
    "me-abudhabi-2" = "rkt"
    "me-abudhabi-3" = "ahu"
    "me-abudhabi-4" = "shj"
    "me-alain-1" = "rba"
    "me-alrayyan-1" = "vve"
    "me-dcc-doha-1" = "doh"
    "me-dcc-muscat-1" = "mct"
    "me-dubai-1" = "dxb"
    "me-ibri-1" = "ibr"
    "me-jeddah-1" = "jed"
    "me-riyadh-1" = "ruh"
    "mx-monterrey-1" = "mty"
    "mx-queretaro-1" = "qro"
    "sa-bogota-1" = "bog"
    "sa-riodejaneiro-1" = "hnw"
    "sa-santiago-1" = "scl"
    "sa-saopaulo-1" = "gru"
    "sa-valparaiso-1" = "vap"
    "sa-vinhedo-1" = "vcp"
    "uk-cardiff-1" = "cwl"
    "uk-gov-cardiff-1" = "brs"
    "uk-gov-london-1" = "ltn"
    "uk-london-1" = "lhr"
    "us-ashburn-1" = "iad"
    "us-ashburn-2" = "yxj"
    "us-chicago-1" = "ord"
    "us-gov-ashburn-1" = "ric"
    "us-gov-chicago-1" = "pia"
    "us-gov-phoenix-1" = "tus"
    "us-langley-1" = "lfi"
    "us-luke-1" = "luf"
    "us-newark-1" = "pgc"
    "us-phoenix-1" = "phx"
    "us-saltlake-2" = "aga"
    "us-sanjose-1" = "sjc"
    "us-somerset-1" = "ebb"
    "us-thames-1" = "ebl"
  }
}

locals {
  oci_region_abbr_map_normalized = {
    for region_name, abbreviation in var.oci_region_abbr_map :
    lower(replace(region_name, "-", "")) => abbreviation
  }

  oci_region_abbr_lookup_map = merge(
    var.oci_region_abbr_map,
    local.oci_region_abbr_map_normalized,
  )
}
