name: Tag

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  tag:
    name: Tag Release
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: '0'

      - name: Validate Terraform Files
        uses: devops-infra/action-tflint@v1.0.5
        with:
          tflint_path: "."

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: 0.0.0
